PMM-1060 add RDS support

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,6 +4,7 @@ set -o errexit
 set -o xtrace
 
 declare -A SERVICES=(
+    ["rds"]="innodb_sb innodb_sb_spike"
     ["md"]="innodb_sb innodb_sb_spike innodb_extra aria_sb deadlock_holder deadlock_requestor defrag_sb defrag_extra onlineddl_sb onlineddl_extra"
     ["ps55"]="innodb_sb innodb_sb_spike innodb_extra myisam_sb myisam_extra small_sb small_extra"
     ["ps56"]="innodb_sb innodb_sb_spike innodb_extra myisam_sb myisam_extra small_sb small_extra"
@@ -35,7 +36,7 @@ remove_all() {
 create_loader() {
     local LOADER=$1
     local SOCKET_PATH=$2
-    local SOCKET_NAME=$(basename $SOCKET_PATH | sed -e 's/.sock$//')
+    local SOCKET_NAME=$(basename $SOCKET_PATH | sed -e 's/[.].*//')
     cat - <<-EOF >/etc/systemd/system/loader-${LOADER}-${SOCKET_NAME}.service
 		[Unit]
 		Description=PMM Loader ${LOADER} for ${SOCKET_NAME} socket
@@ -58,22 +59,28 @@ create_loader() {
 main() {
     local TYPE=$1
     local SOCKET_PATH=$2
-    local SOCKET_NAME=$(basename $SOCKET_PATH | sed -e 's/.sock$//')
+    local SOCKET_NAME=$(basename $SOCKET_PATH | sed -e 's/[.].*//')
 
     if [[ -z "$TYPE" ]] || [[ -z "${SERVICES[$TYPE]}" ]]; then
         echo "unknown server type"
         echo "usage: $0 {ps|pxc|mo|ms|md} /path/to/service.socket"
         exit 1
     fi
-    if [[ -z "$SOCKET_PATH" ]] || [[ ! -S "$SOCKET_PATH" ]]; then
-        echo "cannot find $SOCKET_PATH socket"
+    if [ -S "$SOCKET_PATH" ]; then
+        CONNECTION="--socket=$SOCKET_PATH"
+    elif nslookup "$SOCKET_PATH"; then
+        CONNECTION="--host=$SOCKET_PATH"
+    else
+        echo "cannot find $SOCKET_PATH socket or host"
         echo "usage: $0 {ps|pxc|mo|ms|md} /path/to/service.socket"
         exit 1
     fi
+    CONNECTION+=" --user ${MYSQL_USER:-root}"
+    [ -n "$MYSQL_PASSWORD" ] && CONNECTION+=" -p${MYSQL_PASSWORD}" || :
 
     remove_all "$SOCKET_NAME"
 
-    mysql --user root --socket "${SOCKET_PATH}" < $ROOT_DIR/grants.sql
+    mysql $CONNECTION < $ROOT_DIR/grants.sql
     for LOADER in ${SERVICES[$TYPE]}; do
         create_loader "$LOADER" "$SOCKET_PATH" "$SOCKET_NAME"
     done
